// ==UserScript==
// @name         Blocky
// @namespace    https://github.com/qwgsr/Blocky
// @version      0.1
// @description  DET Website Blocking Userscript
// @author       qwgsr
// @match        http*://*/*
// @grant        none
// ==/UserScript==

var url = "http://"+window.location.hostname
document.head.innerHTML = "";
document.body.innerHTML = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> <html xmlns="http://www.w3.org/1999/xhtml"> <head> <title>Web Site Blocked</title> <style type="text/css"><!-- .body {font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 8pt; color: #000000} .formlabel { font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 8pt; color: #333333; font-weight: bold} .heading {font-family: Verdana, Arial, Helvetica, sans-serif;font-size: 10pt; font-style: normal; font-weight: bold} .alertstopheading { font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 10pt; font-style: normal;font-weight: bold; color: #cc0000} .alertwarningheading {font-family: Verdana, Arial, Helvetica,sans-serif; font-size: 10pt;font-style: normal; font-weight: bold;color: #ff6600} .normal { font-family: Verdana, Arial, Helvetica, sans-serif; } .BlockHeading { font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 50px;font-weight: bold; color:#3366FF } .BlockAllHeading { font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 25px;font-weight: bold; color:#3366FF } --></style> </head> <body bgcolor="#ffffff" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0"> <form id="form1" runat="server"> <div align="center" style="background-color: #ffffff; width: 749px"> <span class="BlockHeading">Blocked Site</span> </div> <table cellspacing="0" cellpadding="0" width="749" border="0"> <tr> <td colspan="2" height="8" bgcolor="#ffffff"> &nbsp;</td> </tr> <tr> <td colspan="2" height="8" bgcolor="#ffffff"> &nbsp;</td> </tr> <tr> <td valign="top" width="112"> <img height="174" width="80" src="http://appserver.det.nsw.edu.au/bfp/images/transparent.gif" /></td> <td valign="top" width="749"> <table cellspacing="0" cellpadding="0" border="0" style="background-color: #ffffff"> <tr> <td width="749" class="normal" style="height: 36px"> <p> The site '+url+' is blocked. It has been classified in the category/ies Suspicious<p>&nbsp;</p><p></p><a href="javascript:history.go(-1)"><img border="0" width="20" height="15" src="http://appserver.det.nsw.edu.au/bfp/images/blue-circle-arrow.gif" /></a>To leave this page please use the <a href="javascript:history.go(-1)">Back</a> browser button or enter a new URL into the browser </p> <p> <p> &nbsp;</p>If your teacher believes this site is required for educational purposes they can request the site to be unblocked. </p> </td> <td class="body" style="height: 36px"> &nbsp;</td> </tr> </table> </td> </tr> </table> <hr /> <p align="center"> </p> <div align="center" style="width: 749px"> <img height="57" src="http://appserver.det.nsw.edu.au/bfp/images/gr_dec_logo.gif" width="163" /></div> </form> </body> </html>';
 
